### ISSUE TITLE
Textures On Server Messed Up

### ISSUE THREAD

**Issue by Diamondman121314** [Wtoll/demeter#10]
When joining a multiplayer server with Demeter installed on the client and not on the server, textures of some blocks get messed up and change into crops. 

With the below screenshots, I use Hypixel's Arcade Lobby to demonstrate.
[Demeter Installed](https://prnt.sc/qirrue)
[Demeter Not Installed](https://prnt.sc/qiruhg)

It seems this isn't the first time this happened either with a mod, as Grondag's Trees Do Not Float mod has the same problem. grondag/trees-dont-float#5

**Comment by Cynosphere** [comment]
Clients and servers get confused when vanilla blocks have non-vanilla blockstates being sent and reading them, thus causing this to happen.

The question now is, do we discuss this upstream, and if so, how upstream? Only to Fabric or should we see if Mojang has any care or use knowing this is an issue? Maybe fixing this bug could become a useful feature in the base game somehow.

**Comment by Wtoll** [comment]
I'm guessing the issue is with the texture atlases and in that case I don't think there's much that can be done. Honestly though if you're playing an instance of the game with Demeter installed and you go to play Hypixel I see that as more of a user error
