### ISSUE TITLE
terraform 1.5.0 incompatible with 1.1.3

### ISSUE THREAD

**Issue by Linguardium** [Wtoll/demeter#14]
terraform (the backend requirement for terrestria, traverse, and vanilla+ biomes) recently added a mixin to the cropblock for watering that conflicts with your mod.

I cannot run both as i CTD. i am not sure what you folks can work out together, but i fear in new versions of terrestria or traverse (or any new biome mod) your mod will fail to work and people will have to choose biomes or plant mod

**Comment by Neubulae** [comment]
Today this happened. cool.
