### ISSUE TITLE
Conflicts with any mod that adds their custom crops

### ISSUE THREAD

**Issue by Neubulae** [Wtoll/demeter#15]
Due to their crops' lack of yield/growth field, the game crashes.
[crash-2020-05-15_15.49.40-server.txt](https://github.com/Wtoll/demeter/files/4633124/crash-2020-05-15_15.49.40-server.txt)

**Comment by Linguardium** [comment]
which crop is it? demeter should be adding the fields via the cropblock appendProperties mixin

**Comment by Neubulae** [comment]
> so Epicurean actually overrides cropblock's append properties and doesnt call super.
> this is an issue with epicurean, as this override should be unnecessary since Age_7 is added by CropBlock and should not be necessary at all in HarvestableCropBlock class.
> 
> https://github.com/CottonMC/Epicurean/blob/7785185002e3d87cb79bd9087131555151634eec/src/main/java/io/github/cottonmc/epicurean/block/crop/HarvestableCropBlock.java#L69

yeah I found that issue and compiled my own version, now it's fine
